apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: testing
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: webserver

