apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mailserver
  name: mailserver
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mailserver
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      containers:
      - image: yagya123/mailserver
        name: mailserver
