apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver
  namespace: default
spec:
  clusterIP: 10.101.117.69
  clusterIPs:
  - 10.101.117.69
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31619
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
